# Generated by Django 4.1.1 on 2023-03-20 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('orderDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Smps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('wattage', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products')),
                ('rate', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cache', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('socket', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=200)),
                ('panel', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.IntegerField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.assemble')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.courier')),
            ],
        ),
        migrations.AddField(
            model_name='assemble',
            name='cabin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.cabin'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='cables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.cables'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.customer'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.display'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='hdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.hdd'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.keyboard'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.motherboard'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.mouse'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.processor'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.ram'),
        ),
        migrations.AddField(
            model_name='assemble',
            name='smps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembleapp.smps'),
        ),
    ]
