# Generated by Django 4.1.1 on 2023-03-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleapp', '0002_alter_customer_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='cables',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='display',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='hdd',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='processor',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='smps',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
