# Generated by Django 4.1.1 on 2023-03-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembleapp', '0005_alter_assemble_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
